# Generated by Django 2.2.5 on 2020-02-08 13:22

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='envoFriendly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meanenvscore', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('productIngredients', models.TextField()),
                ('productCategory', models.CharField(max_length=255)),
                ('productPrice', models.FloatField()),
                ('productAbout', models.TextField()),
                ('envScore', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('productsBought', django.contrib.postgres.fields.jsonb.JSONField()),
                ('avgEnvScore', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
