# Generated by Django 2.2.5 on 2020-02-08 14:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='productsBought',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
    ]
